<a href="https://colab.research.google.com/github/Harini-7907/HariniMowgli/blob/main/Titanic_ML_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [2]:
from google.colab import files

uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [3]:
df = pd.read_csv("titanic.csv")

In [4]:

df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [5]:
df.shape

(891, 12)

In [6]:
df.isnull().sum()

PassengerId      0
Name             0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

In [7]:
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [8]:
df.isnull().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
Survived      0
dtype: int64

In [9]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [10]:
df.isnull().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
Survived      0
dtype: int64

In [11]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [12]:
X = pd.get_dummies(
    X,
    columns=['Sex', 'Embarked'],
    drop_first=True
)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (712, 8)
Testing data: (179, 8)

In [15]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
print("Missing values in X:")
print(X.isnull().sum())

Missing values in X:
Pclass          0
Age           177
SibSp           0
Parch           0
Fare            0
Sex_male        0
Embarked_Q      0
Embarked_S      0
dtype: int64

In [20]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [21]:
print(df.isnull().sum())

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

In [22]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [23]:
X = pd.get_dummies(
    X,
    columns=['Sex', 'Embarked'],
    drop_first=True
)

In [24]:
print(X.isnull().sum())

Pclass        0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_male      0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [25]:
print(X.dtypes)

Pclass          int64
Age           float64
SibSp           int64
Parch           int64
Fare          float64
Sex_male         bool
Embarked_Q       bool
Embarked_S       bool
dtype: object

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [27]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [28]:
print(np.isnan(X_train_scaled).sum())
print(np.isnan(X_test_scaled).sum())

0
0

In [29]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [30]:
knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:", knn_accuracy)

KNN Accuracy: 0.8156424581005587

In [31]:
print(df.isnull().sum())

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

In [32]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf')

svm.fit(X_train_scaled, y_train)

y_pred_svm = svm.predict(X_test_scaled)

svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 0.8100558659217877

In [33]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.7653631284916201

In [34]:
X_train_scaled
X_test_scaled

array([[ 0.82956755, -0.41916965,  1.42175336, ...,  0.74242727,
        -0.28933346,  0.61197825],
       [ 0.82956755,  1.1162898 , -0.46508428, ...,  0.74242727,
        -0.28933346,  0.61197825],
       [ 0.82956755, -0.57271559, -0.46508428, ...,  0.74242727,
        -0.28933346, -1.63404501],
       ...,
       [-0.37094484, -0.11207776, -0.46508428, ...,  0.74242727,
        -0.28933346,  0.61197825],
       [-0.37094484, -0.49594262, -0.46508428, ..., -1.34693328,
        -0.28933346, -1.63404501],
       [-0.37094484,  0.11824116,  0.47833454, ...,  0.74242727,
        -0.28933346,  0.61197825]])

In [35]:
X_train
X_test

     Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
565       3  24.0      2      0  24.1500      True       False        True
160       3  44.0      0      1  16.1000      True       False        True
553       3  22.0      0      0   7.2250      True       False       False
860       3  41.0      2      0  14.1083      True       False        True
241       3  28.0      1      0  15.5000     False        True       False
..      ...   ...    ...    ...      ...       ...         ...         ...
880       2  25.0      0      1  26.0000     False       False        True
91        3  20.0      0      0   7.8542      True       False        True
883       2  28.0      0      0  10.5000      True       False        True
473       2  23.0      0      0  13.7917     False       False       False
637       2  31.0      1      1  26.2500      True       False        True

[179 rows x 8 columns]

In [38]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.8156424581005587